name: "dotnet-format-format"

description: "Run dotnet format and optionally apply any fixes"

author:
  - "jfversluis"
  - "xt0rted"
  - "victor-alcazar"
  - "eero-dev"

branding:
  icon: "file-text"
  color: "blue"

inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true

  action:
    description: "The primary action `dotnet format` should perform. `check` for only checking, `fix` will also actually fix the formatting errors in the files."
    required: false
    default: "check"

  only-changed-files:
    description: "Only changed files in the current pull request should be formatted. Only works when the trigger is a pull request."
    required: false

  fail-fast:
    description: "The job should fail if there's a formatting error."
    required: false
    default: "true"

  workspace:
    description: "The solution or project file to operate on."
    required: true

  include:
    description: "The files to include, delimited by space."
    required: false

  exclude:
    description: "The files to exclude, delimited by space."
    required: false

  fix-whitespace:
    description: "Removes whitespaces according to formatting rules."
    required: false

  fix-analyzers-level:
    description: "Fixes styles from third-party analyzers. More on https://github.com/dotnet/format/blob/main/docs/3rd-party-analyzers.md"
    required: false

  fix-style-level:
    description: "Fixes styles according to formating rules."
    required: false

  log-level:
    description: "Sets the logging verbosity of the dotnet format process. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]"
    required: false

outputs:
  has-changes:
    description: "A value indicating if any files were formatted. If `action` is `check` we will inspect the exit code of `dotnet format` to be <> 0. If `action` is `fix` we see if there are changes to files with `git status -s`."

runs:
  using: "node20"
  main: "dist/index.js"
