name: Pull Request

on: pull_request

jobs:
  message-check:
    name: Block Autosquash Commits

    runs-on: ubuntu-latest

    steps:
      - name: Block Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@46d5b0b278061ef15ff5e8c74ad83a0615df3f1d
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
